### ISSUE TITLE
Exchanging a code against an access token "ERROR"

### ISSUE THREAD

**Issue by dmarkKd** [zf-fr/zfr-shopify#64]
http://prntscr.com/gk81mz
how to fix this issue

**Comment by bakura10** [comment]
Hi,

I'd suggest you to read the documentation here: https://help.shopify.com/api/getting-started/authentication/oauth

As your issue is more related to Shopify API itself, I'd recommend you to post to the Shopify forum: https://ecommerce.shopify.com/c/shopify-apis-and-technology

I'm closing this issue for now :).
