### ISSUE TITLE
Feature Request: Cursor Based Pagination in API resources

### ISSUE THREAD

**Issue by efficientbit** [zf-fr/zfr-shopify#96]
HI @bakura10 
Hope you are well. As you know Shopify has introduced API Versioning which you fixed previously. I really appreciate your addition of versioning in this package. From API version '2019-07' Shopify has deprecated "page" based pagination and has introduced "cursor-based pagination".  
Please read these two articles:
- https://help.shopify.com/en/api/versioning
- https://help.shopify.com/en/api/guides/paginated-rest-results

I would like to request the following things
- Add a function like "getResponseHeaders()" so we can get response headers after calling of each command
- Or in the response to each command return header response as well.
- Or after calling commands like "getProducts()" or "getOrders()". In response add "next" and "previous" links as well.

**Comment by bakura10** [comment]
Hi !

Sorry for the late reply, I'm currently not available for 1 week (holiday) so I won't be able to reply in great detail, but:

* ZfrShopify has always used cursor-based pagination so there is normally nothing to do in this regarde: https://github.com/zf-fr/zfr-shopify/blob/master/src/ShopifyClient.php#L608
* Adding a getResponseHeaders is not really something i'd like to do, as it would make code a bit hard to understand (as the result of this function would depend on the last call you do). I'm not in favor of exposing the response headers.

If you want to build the pagination yourself, you can do it yourself by getting the ID of the last object you retrieve, or simply use the *Iterator variant (getProductsIterator()) which will handle this pagination for you automatically: https://github.com/zf-fr/zfr-shopify#using-iterators

**Comment by EatBreatheCode** [comment]
Hi @bakura10, please revisit this, or at the very least indicate how you would expose the response headers. For MOST methods Shopify NO LONGER allows for page based pagination as clearly indicated in their documentation.
![image](https://user-images.githubusercontent.com/20159826/72116110-2bc7cc00-3317-11ea-8396-2e69498026d9.png)

**Comment by bakura10** [comment]
Hi,

I thought that while page was being deprecated, since_id was not. The paginator does not use page at all (it uses since_id: https://github.com/zf-fr/zfr-shopify/blob/master/src/ShopifyClient.php#L633).

I'm not doing PHP development for several years now, so it's a bit hard for me to maintain this library especially since the rapid pace of Shopify API now. Can you please confirm me that since_id does not work neither on those endpoints?

**Comment by EatBreatheCode** [comment]
I can indeed confirm that it does not. I have spent several ours trying to resolve this myself as we use your library in production. Is there any way you can show me to reveal these response headers using Guzzle? I don't mind doing the rest.

**Comment by bakura10** [comment]
@EatBreatheCode , first of all I've tried and it seems the since_id is still supported. I've tried various endpoints and it is still listed on official documentation for the last version.

I have also works on a way to extract the data from the repsonse, parse it, and expose it to a hash under the key "pagination" along the other attributes inside each objects. You can try the PR here: https://github.com/zf-fr/zfr-shopify/pull/98

There are various drawbacks though:

* As of today the info is added to each objects, the semantic is a bit odd (I thought of changing the way objects are returned so that when you get let's say products, instead of returning an array, it would return an array that contains two keys: pagination and objects for instance). But this would be a massive breaking change as the way you access the objects is no longer the same.
* This also kinda defeat the point as while the info would be here, it would force you to manually do the API call, hence not taking any advantage of the abstraction.

Ultimately, I still think thta the pagination data should not be exposed as part of this library. This library is meant to be a high level library to consume the Shopify API. If you need to get the headers, you should directly use a bare Guzzle client and do the requests manually.

The best here would be to extract the logic in the method that does the iteration (here https://github.com/zf-fr/zfr-shopify/blob/master/src/ShopifyClient.php#L605), so that the iterate method extract the header link and do the next call (instead of relying on the "since_id" here).

As said though I don't work with PHP for several years now and I have very limited time to work and maintain on this. The PR I did (I won't merge it due to the various limitations, but that can give you some idea on how you could implement it). If you can work on a PR to update the pagination part here (https://github.com/zf-fr/zfr-shopify/blob/master/src/ShopifyClient.php#L605) I'd be happy to have a closer look at it and review.

**Comment by EatBreatheCode** [comment]
Thank you so much for the detailed response! As stated, although somewhat familiar with Guzzle, I've  spent hours without success trying to acquire `page_info` value from the response header.
See here https://help.shopify.com/en/api/guides/paginated-rest-results.
![image](https://user-images.githubusercontent.com/20159826/72176539-970fad80-33ac-11ea-905f-ca8b43bf16e0.png)

If you could provide even a small snippet of code indicating how to expose the Guzzle header values, I can take care of implementing it within the iteration method. I've tried dumping the `GuzzleClient` being created but can't seem to make sense of it at the moment.

Thanks again, your feedback is greatly appreciated :)

**Comment by bakura10** [comment]
Hi everyone,

I've worked today on a better implementation of this and it is available in this PR: https://github.com/zf-fr/zfr-shopify/pull/98

In order to be safe, this will be tagged as the version 6. I would suggest you to try this PR first and make sure to report me any issue.

As per this library phillosophy, it _will not_ expose the header for you. If you want to get the header, please use a bare Guzzle client to do yourself the HTTP requests.

However, when you are using any iterator based approach, it will now uses the link based approach instead of the "since_id" approach. The usage has not changed, so to iterate through all products for instance, you simply do:

```php
foreach ($client->getProductsIterator(['fields' => 'id,title']) as $product) {
   // Use the product
});
```

However under the hood, the library will now use the Link to extract the next page and do the next request, until there is no more results left.

As this issue is now addressed, I'm closing this issue. Please continue the conversation if the PR.

**Comment by bakura10** [comment]
@EatBreatheCode , did you have time to check if my PR solved the issue?

**Comment by EatBreatheCode** [comment]
It sure did! Thanks a ton :)
